{% set name = "php" %}
{% set version = "8.0.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.php.net/distributions/{{ name }}-{{ version }}.tar.gz
  sha256: c6a461f57b4bcb46cd4dec443253b1e2e8e981466f1280093322b7864afe8be7
  patches:
    - 0005-iconv_basic_001.phpt-iconv-update.patch
    - 0006-bug61367-read.phpt-libxml2-update.patch
    - 0007-libxml_disable_entity_loader.phpt-libxml2-update.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - bison
    - libtool
    - pkg-config
    - util-linux
  host:
    - libiconv
    - libxml2
    - openssl
    - re2c
    - sqlite

test:
  commands:
    - php --version
    - php --help

about:
  home: https://github.com/php/php-src
  license: PHP-3.01
  license_family: OTHER
  license_file: LICENSE
  summary: PHP is a popular general-purpose scripting language that is especially suited to web development.
  description: |
    PHP is a popular general-purpose scripting language that is especially suited to web development. 
    Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world. 
    PHP is distributed under the PHP License v3.01.
  doc_url: https://www.php.net/
  dev_url: https://github.com/php/php-src

extra:
  recipe-maintainers:
    - fhoehle
