bot:
  abi_migration_branches:
  - 7.3.x
  - 7.4.x
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
conda_build:
  pkg_format: '2'
